"""empty message

Revision ID: 29bbf8a43822
Revises: 538063460cc8
Create Date: 2014-07-25 00:44:43.049060

"""

# revision identifiers, used by Alembic.
revision = '29bbf8a43822'
down_revision = '538063460cc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
