"""empty message

Revision ID: 538063460cc8
Revises: 271993968ecf
Create Date: 2014-07-25 00:39:34.859698

"""

# revision identifiers, used by Alembic.
revision = '538063460cc8'
down_revision = '271993968ecf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
